/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { Minting, MintingInterface } from "../Minting";

const _abi = [
  {
    inputs: [],
    name: "amount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
    ],
    name: "indexes",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class Minting__factory {
  static readonly abi = _abi;
  static createInterface(): MintingInterface {
    return new utils.Interface(_abi) as MintingInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Minting {
    return new Contract(address, _abi, signerOrProvider) as Minting;
  }
}
