/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface TokenConverterInterface extends ethers.utils.Interface {
  functions: {
    "DEFAULT_FACTORY()": FunctionFragment;
    "DEFAULT_ROUTER()": FunctionFragment;
    "WETH()": FunctionFragment;
    "checkTokensDistance(address,address)": FunctionFragment;
    "checkTokensDistanceByFactory(address,address,address)": FunctionFragment;
    "checkTokensDistanceByRouter(address,address,address)": FunctionFragment;
    "convertChained(address[],uint256)": FunctionFragment;
    "convertChainedByFactory(address,address[],uint256)": FunctionFragment;
    "convertChainedByRouter(address,address[],uint256)": FunctionFragment;
    "convertChainedUniversal(address[],uint256)": FunctionFragment;
    "convertChainedUniversalByFactory(address,address[],uint256)": FunctionFragment;
    "convertChainedUniversalByRouter(address,address[],uint256)": FunctionFragment;
    "convertTwo(address,address,uint256)": FunctionFragment;
    "convertTwoByFactory(address,address,address,uint256)": FunctionFragment;
    "convertTwoByPair(address,uint256,address)": FunctionFragment;
    "convertTwoByRouter(address,address,address,uint256)": FunctionFragment;
    "convertTwoUniversal(address,address,uint256)": FunctionFragment;
    "convertTwoUniversalByFactory(address,address,address,uint256)": FunctionFragment;
    "convertTwoUniversalByRouter(address,address,address,uint256)": FunctionFragment;
    "convertViaWETH(address,address,uint256)": FunctionFragment;
    "convertViaWETHByFactory(address,address,address,uint256)": FunctionFragment;
    "convertViaWETHByRouter(address,address,address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "DEFAULT_FACTORY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ROUTER",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "WETH", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "checkTokensDistance",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "checkTokensDistanceByFactory",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "checkTokensDistanceByRouter",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "convertChained",
    values: [string[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "convertChainedByFactory",
    values: [string, string[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "convertChainedByRouter",
    values: [string, string[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "convertChainedUniversal",
    values: [string[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "convertChainedUniversalByFactory",
    values: [string, string[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "convertChainedUniversalByRouter",
    values: [string, string[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "convertTwo",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "convertTwoByFactory",
    values: [string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "convertTwoByPair",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "convertTwoByRouter",
    values: [string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "convertTwoUniversal",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "convertTwoUniversalByFactory",
    values: [string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "convertTwoUniversalByRouter",
    values: [string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "convertViaWETH",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "convertViaWETHByFactory",
    values: [string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "convertViaWETHByRouter",
    values: [string, string, string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_FACTORY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ROUTER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "WETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkTokensDistance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkTokensDistanceByFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkTokensDistanceByRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "convertChained",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "convertChainedByFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "convertChainedByRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "convertChainedUniversal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "convertChainedUniversalByFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "convertChainedUniversalByRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "convertTwo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "convertTwoByFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "convertTwoByPair",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "convertTwoByRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "convertTwoUniversal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "convertTwoUniversalByFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "convertTwoUniversalByRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "convertViaWETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "convertViaWETHByFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "convertViaWETHByRouter",
    data: BytesLike
  ): Result;

  events: {};
}

export class TokenConverter extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: TokenConverterInterface;

  functions: {
    DEFAULT_FACTORY(overrides?: CallOverrides): Promise<[string]>;

    DEFAULT_ROUTER(overrides?: CallOverrides): Promise<[string]>;

    WETH(overrides?: CallOverrides): Promise<[string]>;

    checkTokensDistance(
      _tokenA: string,
      _tokenB: string,
      overrides?: CallOverrides
    ): Promise<[number]>;

    checkTokensDistanceByFactory(
      _factory: string,
      _tokenA: string,
      _tokenB: string,
      overrides?: CallOverrides
    ): Promise<[number]>;

    checkTokensDistanceByRouter(
      _router: string,
      _tokenA: string,
      _tokenB: string,
      overrides?: CallOverrides
    ): Promise<[number]>;

    convertChained(
      _tokens: string[],
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { amt: BigNumber }>;

    convertChainedByFactory(
      _factory: string,
      _tokens: string[],
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { amt: BigNumber }>;

    convertChainedByRouter(
      _router: string,
      _tokens: string[],
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { amt: BigNumber }>;

    convertChainedUniversal(
      _tokens: string[],
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { amt: BigNumber }>;

    convertChainedUniversalByFactory(
      _factory: string,
      _tokens: string[],
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { amt: BigNumber }>;

    convertChainedUniversalByRouter(
      _router: string,
      _tokens: string[],
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { amt: BigNumber }>;

    convertTwo(
      _tokenA: string,
      _tokenB: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    convertTwoByFactory(
      _factory: string,
      _tokenA: string,
      _tokenB: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    convertTwoByPair(
      _tokenA: string,
      _amount: BigNumberish,
      _pair: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    convertTwoByRouter(
      _router: string,
      _tokenA: string,
      _tokenB: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    convertTwoUniversal(
      _tokenA: string,
      _tokenB: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    convertTwoUniversalByFactory(
      _factory: string,
      _tokenA: string,
      _tokenB: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    convertTwoUniversalByRouter(
      _router: string,
      _tokenA: string,
      _tokenB: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    convertViaWETH(
      _tokenA: string,
      _tokenB: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    convertViaWETHByFactory(
      _factory: string,
      _tokenA: string,
      _tokenB: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    convertViaWETHByRouter(
      _router: string,
      _tokenA: string,
      _tokenB: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  DEFAULT_FACTORY(overrides?: CallOverrides): Promise<string>;

  DEFAULT_ROUTER(overrides?: CallOverrides): Promise<string>;

  WETH(overrides?: CallOverrides): Promise<string>;

  checkTokensDistance(
    _tokenA: string,
    _tokenB: string,
    overrides?: CallOverrides
  ): Promise<number>;

  checkTokensDistanceByFactory(
    _factory: string,
    _tokenA: string,
    _tokenB: string,
    overrides?: CallOverrides
  ): Promise<number>;

  checkTokensDistanceByRouter(
    _router: string,
    _tokenA: string,
    _tokenB: string,
    overrides?: CallOverrides
  ): Promise<number>;

  convertChained(
    _tokens: string[],
    _amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  convertChainedByFactory(
    _factory: string,
    _tokens: string[],
    _amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  convertChainedByRouter(
    _router: string,
    _tokens: string[],
    _amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  convertChainedUniversal(
    _tokens: string[],
    _amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  convertChainedUniversalByFactory(
    _factory: string,
    _tokens: string[],
    _amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  convertChainedUniversalByRouter(
    _router: string,
    _tokens: string[],
    _amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  convertTwo(
    _tokenA: string,
    _tokenB: string,
    _amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  convertTwoByFactory(
    _factory: string,
    _tokenA: string,
    _tokenB: string,
    _amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  convertTwoByPair(
    _tokenA: string,
    _amount: BigNumberish,
    _pair: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  convertTwoByRouter(
    _router: string,
    _tokenA: string,
    _tokenB: string,
    _amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  convertTwoUniversal(
    _tokenA: string,
    _tokenB: string,
    _amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  convertTwoUniversalByFactory(
    _factory: string,
    _tokenA: string,
    _tokenB: string,
    _amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  convertTwoUniversalByRouter(
    _router: string,
    _tokenA: string,
    _tokenB: string,
    _amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  convertViaWETH(
    _tokenA: string,
    _tokenB: string,
    _amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  convertViaWETHByFactory(
    _factory: string,
    _tokenA: string,
    _tokenB: string,
    _amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  convertViaWETHByRouter(
    _router: string,
    _tokenA: string,
    _tokenB: string,
    _amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    DEFAULT_FACTORY(overrides?: CallOverrides): Promise<string>;

    DEFAULT_ROUTER(overrides?: CallOverrides): Promise<string>;

    WETH(overrides?: CallOverrides): Promise<string>;

    checkTokensDistance(
      _tokenA: string,
      _tokenB: string,
      overrides?: CallOverrides
    ): Promise<number>;

    checkTokensDistanceByFactory(
      _factory: string,
      _tokenA: string,
      _tokenB: string,
      overrides?: CallOverrides
    ): Promise<number>;

    checkTokensDistanceByRouter(
      _router: string,
      _tokenA: string,
      _tokenB: string,
      overrides?: CallOverrides
    ): Promise<number>;

    convertChained(
      _tokens: string[],
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    convertChainedByFactory(
      _factory: string,
      _tokens: string[],
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    convertChainedByRouter(
      _router: string,
      _tokens: string[],
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    convertChainedUniversal(
      _tokens: string[],
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    convertChainedUniversalByFactory(
      _factory: string,
      _tokens: string[],
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    convertChainedUniversalByRouter(
      _router: string,
      _tokens: string[],
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    convertTwo(
      _tokenA: string,
      _tokenB: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    convertTwoByFactory(
      _factory: string,
      _tokenA: string,
      _tokenB: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    convertTwoByPair(
      _tokenA: string,
      _amount: BigNumberish,
      _pair: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    convertTwoByRouter(
      _router: string,
      _tokenA: string,
      _tokenB: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    convertTwoUniversal(
      _tokenA: string,
      _tokenB: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    convertTwoUniversalByFactory(
      _factory: string,
      _tokenA: string,
      _tokenB: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    convertTwoUniversalByRouter(
      _router: string,
      _tokenA: string,
      _tokenB: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    convertViaWETH(
      _tokenA: string,
      _tokenB: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    convertViaWETHByFactory(
      _factory: string,
      _tokenA: string,
      _tokenB: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    convertViaWETHByRouter(
      _router: string,
      _tokenA: string,
      _tokenB: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    DEFAULT_FACTORY(overrides?: CallOverrides): Promise<BigNumber>;

    DEFAULT_ROUTER(overrides?: CallOverrides): Promise<BigNumber>;

    WETH(overrides?: CallOverrides): Promise<BigNumber>;

    checkTokensDistance(
      _tokenA: string,
      _tokenB: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkTokensDistanceByFactory(
      _factory: string,
      _tokenA: string,
      _tokenB: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkTokensDistanceByRouter(
      _router: string,
      _tokenA: string,
      _tokenB: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    convertChained(
      _tokens: string[],
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    convertChainedByFactory(
      _factory: string,
      _tokens: string[],
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    convertChainedByRouter(
      _router: string,
      _tokens: string[],
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    convertChainedUniversal(
      _tokens: string[],
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    convertChainedUniversalByFactory(
      _factory: string,
      _tokens: string[],
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    convertChainedUniversalByRouter(
      _router: string,
      _tokens: string[],
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    convertTwo(
      _tokenA: string,
      _tokenB: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    convertTwoByFactory(
      _factory: string,
      _tokenA: string,
      _tokenB: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    convertTwoByPair(
      _tokenA: string,
      _amount: BigNumberish,
      _pair: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    convertTwoByRouter(
      _router: string,
      _tokenA: string,
      _tokenB: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    convertTwoUniversal(
      _tokenA: string,
      _tokenB: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    convertTwoUniversalByFactory(
      _factory: string,
      _tokenA: string,
      _tokenB: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    convertTwoUniversalByRouter(
      _router: string,
      _tokenA: string,
      _tokenB: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    convertViaWETH(
      _tokenA: string,
      _tokenB: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    convertViaWETHByFactory(
      _factory: string,
      _tokenA: string,
      _tokenB: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    convertViaWETHByRouter(
      _router: string,
      _tokenA: string,
      _tokenB: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    DEFAULT_FACTORY(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    DEFAULT_ROUTER(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    WETH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    checkTokensDistance(
      _tokenA: string,
      _tokenB: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkTokensDistanceByFactory(
      _factory: string,
      _tokenA: string,
      _tokenB: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkTokensDistanceByRouter(
      _router: string,
      _tokenA: string,
      _tokenB: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    convertChained(
      _tokens: string[],
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    convertChainedByFactory(
      _factory: string,
      _tokens: string[],
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    convertChainedByRouter(
      _router: string,
      _tokens: string[],
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    convertChainedUniversal(
      _tokens: string[],
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    convertChainedUniversalByFactory(
      _factory: string,
      _tokens: string[],
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    convertChainedUniversalByRouter(
      _router: string,
      _tokens: string[],
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    convertTwo(
      _tokenA: string,
      _tokenB: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    convertTwoByFactory(
      _factory: string,
      _tokenA: string,
      _tokenB: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    convertTwoByPair(
      _tokenA: string,
      _amount: BigNumberish,
      _pair: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    convertTwoByRouter(
      _router: string,
      _tokenA: string,
      _tokenB: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    convertTwoUniversal(
      _tokenA: string,
      _tokenB: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    convertTwoUniversalByFactory(
      _factory: string,
      _tokenA: string,
      _tokenB: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    convertTwoUniversalByRouter(
      _router: string,
      _tokenA: string,
      _tokenB: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    convertViaWETH(
      _tokenA: string,
      _tokenB: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    convertViaWETHByFactory(
      _factory: string,
      _tokenA: string,
      _tokenB: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    convertViaWETHByRouter(
      _router: string,
      _tokenA: string,
      _tokenB: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
