/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { Burnable, BurnableInterface } from "../Burnable";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "burn",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class Burnable__factory {
  static readonly abi = _abi;
  static createInterface(): BurnableInterface {
    return new utils.Interface(_abi) as BurnableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Burnable {
    return new Contract(address, _abi, signerOrProvider) as Burnable;
  }
}
